import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ComposableMap,Geographies,Geography}from"react-simple-maps";import"./styles.css";
const GEO="https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";
type Option={name:string;pct:number};type Poll={question:string;category:string;options:Option[];votes:number};
const polls:Poll[]=[
{question:"Which country do you personally consider the most imperialist today?",category:"Geopolitics",options:[{name:"United States",pct:38},{name:"Russia",pct:24},{name:"China",pct:19},{name:"France",pct:7},{name:"Other",pct:12}],votes:52481},
{question:"Should nuclear weapons be abolished worldwide?",category:"Security",options:[{name:"Yes",pct:61},{name:"No",pct:29},{name:"Unsure",pct:10}],votes:31806},
{question:"Has globalization benefited your country overall?",category:"Economics",options:[{name:"Yes",pct:53},{name:"No",pct:34},{name:"Unsure",pct:13}],votes:27712},
{question:"Which institution do you personally trust most to address global crises?",category:"Institutions",options:[{name:"United Nations",pct:35},{name:"National governments",pct:27},{name:"NGOs",pct:20},{name:"None",pct:18}],votes:19044},
{question:"Should countries accept more refugees during major humanitarian crises?",category:"Migration",options:[{name:"Yes",pct:48},{name:"No",pct:39},{name:"Unsure",pct:13}],votes:23409}
];
const colors=["#65e6c4","#54a8ff","#a47cff","#ffc15a","#f07ea3"];
function App(){const[index,setIndex]=useState(0);const[choice,setChoice]=useState<string|null>(null);const p=polls[index];const advance=(d=1)=>{setIndex((index+d+polls.length)%polls.length);setChoice(null)};return <main><nav><div className="brand"><i/>WorldPolls</div><div className="navRight"><span>GLOBAL OPINION ATLAS</span><b>{(index+1).toString().padStart(2,"0")} / {polls.length.toString().padStart(2,"0")}</b></div></nav><section className="layout"><article><div className="eyebrow"><span>{p.category}</span><i/> LIVE QUESTION</div><h1>{p.question}</h1><p className="dek">Give your view before seeing the aggregate. Results unlock immediately after you vote.</p>{!choice?<div className="options">{p.options.map((o,n)=><button key={o.name} onClick={()=>setChoice(o.name)}><span><em>{String.fromCharCode(65+n)}</em>{o.name}</span><strong>Choose</strong></button>)}</div>:<div className="results"><div className="resultTitle"><div><small>GLOBAL RESULTS</small><h2>{p.votes.toLocaleString()} responses</h2></div><span>DEMO DATA</span></div>{p.options.map((o,n)=><div className="result" key={o.name}><div><span>{o.name}{choice===o.name&&<small> YOUR VOTE</small>}</span><b>{o.pct}%</b></div><div className="track"><i style={{width:o.pct+"%",background:colors[n%colors.length]}}/></div></div>)}<button className="continue" onClick={()=>advance()}>Next question <b>→</b></button></div>}<div className="pager"><button onClick={()=>advance(-1)}>←</button><div>{polls.map((_,n)=><i key={n} className={n===index?"active":""}/>)}</div><button onClick={()=>advance()}>→</button></div></article><aside><div className="mapHeader"><div><small>WORLD VIEW</small><b>{choice?"Results unlocked":"Results hidden"}</b></div><div className={choice?"status live":"status"}><i/>{choice?"EXPLORE":"VOTE FIRST"}</div></div><div className="map"><ComposableMap projectionConfig={{scale:145}} width={800} height={470}><Geographies geography={GEO}>{({geographies})=>geographies.map((geo:any)=><Geography key={geo.rsmKey} geography={geo} fill={choice?"#163d4b":"#12283a"} stroke="#557083" strokeWidth={.45} style={{default:{outline:"none"},hover:{fill:"#65e6c4",outline:"none"},pressed:{outline:"none"}}}/>)}</Geographies></ComposableMap></div><div className="mapFooter"><span>{choice?"Country-level breakdowns are the next data layer":"Aggregate results remain hidden until you answer"}</span><b>WORLD · 2026</b></div></aside></section><footer><div><b>Methodology matters.</b> Prototype results are illustrative and are not scientific polling.</div><div>Production should disclose sample composition, field dates, weighting and anti-brigading methods.</div></footer></main>}createRoot(document.getElementById("root")!).render(<App/>);